name: Typescript App setup

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'dev'

env:
  PACKAGE_DIRECTORY: '.'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (selected branch)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'                            # <- was 'npm'
          cache-dependency-path: pnpm-lock.yaml    # <- points to your lockfile

      - name: Enable Corepack & ensure pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate       # or the version you use

      - name: Cache node_modules (keyed by lockfile)
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.cache/pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        working-directory: ${{ env.PACKAGE_DIRECTORY }}
        shell: bash
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          elif [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
