name: Typescript App setup

on:
  workflow_dispatch:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'dev'

env:
  PACKAGE_DIRECTORY: '.'
  NODE_VERSION: '20.x' # LTS suitable for most TS/React builds


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (selected branch)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # ---------- TypeScript build pipeline ----------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack (pnpm/yarn support)
        run: corepack enable

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.cache/pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        working-directory: ${{ env.PACKAGE_DIRECTORY }}
        shell: bash
        run: pnpm install --frozen-lockfile